[2024-07-30T18:23:27.039+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:23:27.040+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:23:27.043+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:23:27.042+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:23:27.067+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:23:27.062+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:23:27.068+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:23:27.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.093 seconds
[2024-07-30T18:26:05.642+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:05.643+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:26:05.645+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:26:05.644+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:05.655+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:26:05.653+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:26:05.656+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:05.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.076 seconds
[2024-07-30T18:26:36.054+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:36.055+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:26:36.056+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:26:36.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:36.074+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:26:36.066+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:26:36.075+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:36.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.094 seconds
[2024-07-30T18:26:57.889+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:57.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:26:57.891+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:26:57.890+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:57.898+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:26:57.896+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:26:57.899+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:26:57.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.069 seconds
[2024-07-30T18:27:28.257+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:27:28.258+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:27:28.259+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:27:28.258+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:27:28.269+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:27:28.267+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:27:28.269+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:27:28.332+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.079 seconds
[2024-07-30T18:27:58.635+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:27:58.636+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:27:58.637+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:27:58.637+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:27:58.657+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:27:58.650+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:27:58.658+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:27:58.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.090 seconds
[2024-07-30T18:28:25.790+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:28:25.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:28:25.795+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:28:25.794+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:28:25.807+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:28:25.802+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:28:25.808+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:28:25.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.082 seconds
[2024-07-30T18:28:56.118+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:28:56.120+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:28:56.122+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:28:56.121+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:28:56.139+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:28:56.135+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:28:56.140+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:28:56.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.148 seconds
[2024-07-30T18:29:14.238+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:29:14.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:29:14.246+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:29:14.242+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:29:14.260+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:29:14.257+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:29:14.261+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:29:14.323+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.090 seconds
[2024-07-30T18:29:44.598+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:29:44.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:29:44.600+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:29:44.599+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:29:44.609+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:29:44.607+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:29:44.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:29:44.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.083 seconds
[2024-07-30T18:30:14.947+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:30:14.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:30:14.949+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:30:14.949+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:30:14.957+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:30:14.955+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:30:14.958+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:30:15.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.076 seconds
[2024-07-30T18:30:45.397+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:30:45.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:30:45.399+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:30:45.399+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:30:45.411+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:30:45.408+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:30:45.412+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:30:45.482+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.088 seconds
[2024-07-30T18:31:15.817+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:15.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:31:15.820+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:31:15.819+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:15.831+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:31:15.829+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:31:15.832+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:15.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.078 seconds
[2024-07-30T18:31:46.230+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:46.231+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:31:46.232+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:31:46.231+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:46.240+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:31:46.238+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:31:46.241+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:46.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.080 seconds
[2024-07-30T18:31:58.974+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:58.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:31:58.976+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:31:58.975+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:58.992+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:31:58.989+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:31:58.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:31:59.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.088 seconds
[2024-07-30T18:42:26.798+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:42:26.800+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:42:26.802+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:42:26.801+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:42:26.817+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:42:26.813+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:42:26.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:42:26.881+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.086 seconds
[2024-07-30T18:42:57.128+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:42:57.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:42:57.131+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:42:57.131+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:42:57.146+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:42:57.142+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:42:57.147+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:42:57.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.095 seconds
[2024-07-30T18:43:27.503+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:43:27.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:43:27.505+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:43:27.505+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:43:27.514+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:43:27.512+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:43:27.514+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:43:27.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.078 seconds
[2024-07-30T18:43:58.000+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:43:58.001+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:43:58.003+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:43:58.002+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:43:58.013+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:43:58.011+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:43:58.013+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:43:58.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.084 seconds
[2024-07-30T18:44:28.382+0000] {processor.py:157} INFO - Started process (PID=186) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:44:28.383+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:44:28.384+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:44:28.383+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:44:28.393+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:44:28.391+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:44:28.394+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:44:28.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.075 seconds
[2024-07-30T18:44:58.741+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:44:58.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:44:58.743+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:44:58.742+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:44:58.752+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:44:58.750+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:44:58.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:44:58.814+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.076 seconds
[2024-07-30T18:45:39.886+0000] {processor.py:157} INFO - Started process (PID=166) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:45:39.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:45:39.890+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:45:39.889+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:45:39.900+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:45:39.898+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:45:39.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:45:39.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.077 seconds
[2024-07-30T18:46:10.194+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:46:10.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:46:10.197+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:46:10.196+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:46:10.220+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:46:10.206+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:46:10.221+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:46:10.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.104 seconds
[2024-07-30T18:46:40.553+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:46:40.553+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:46:40.554+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:46:40.554+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:46:40.562+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:46:40.560+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:46:40.562+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:46:40.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.077 seconds
[2024-07-30T18:47:10.880+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:47:10.881+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:47:10.882+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:47:10.882+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:47:10.894+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:47:10.891+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:47:10.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:47:10.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.085 seconds
[2024-07-30T18:47:41.323+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:47:41.324+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:47:41.325+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:47:41.325+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:47:41.333+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:47:41.332+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:47:41.334+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:47:41.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.077 seconds
[2024-07-30T18:48:11.721+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:48:11.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:48:11.723+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:48:11.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:48:11.731+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:48:11.730+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:48:11.732+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:48:11.794+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.077 seconds
[2024-07-30T18:48:42.174+0000] {processor.py:157} INFO - Started process (PID=197) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:48:42.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:48:42.175+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:48:42.175+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:48:42.182+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:48:42.180+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:48:42.182+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:48:42.242+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.071 seconds
[2024-07-30T18:49:12.545+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:49:12.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:49:12.547+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:49:12.547+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:49:12.555+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:49:12.553+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:49:12.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:49:12.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.076 seconds
[2024-07-30T18:49:42.957+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:49:42.958+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:49:42.959+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:49:42.958+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:49:42.966+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:49:42.965+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:49:42.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:49:43.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.074 seconds
[2024-07-30T18:50:13.317+0000] {processor.py:157} INFO - Started process (PID=212) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:50:13.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:50:13.318+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:50:13.318+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:50:13.323+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:50:13.322+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:50:13.323+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:50:13.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.060 seconds
[2024-07-30T18:50:43.777+0000] {processor.py:157} INFO - Started process (PID=217) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:50:43.778+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:50:43.779+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:50:43.778+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:50:43.786+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:50:43.784+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:50:43.786+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:50:43.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.073 seconds
[2024-07-30T18:51:14.158+0000] {processor.py:157} INFO - Started process (PID=222) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:51:14.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:51:14.160+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:51:14.160+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:51:14.168+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:51:14.166+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:51:14.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:51:14.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.075 seconds
[2024-07-30T18:51:44.530+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:51:44.530+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:51:44.531+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:51:44.531+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:51:44.537+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:51:44.535+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:51:44.537+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:51:44.598+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.071 seconds
[2024-07-30T18:52:14.889+0000] {processor.py:157} INFO - Started process (PID=232) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:52:14.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:52:14.890+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:52:14.890+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:52:14.898+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:52:14.896+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:52:14.898+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:52:14.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.071 seconds
[2024-07-30T18:52:45.222+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:52:45.223+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:52:45.223+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:52:45.223+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:52:45.229+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:52:45.228+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:52:45.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:52:45.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.069 seconds
[2024-07-30T18:53:15.598+0000] {processor.py:157} INFO - Started process (PID=242) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:53:15.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:53:15.600+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:53:15.599+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:53:15.610+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:53:15.608+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:53:15.611+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:53:15.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.110 seconds
[2024-07-30T18:53:45.917+0000] {processor.py:157} INFO - Started process (PID=247) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:53:45.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:53:45.919+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:53:45.918+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:53:45.925+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:53:45.924+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:53:45.926+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:53:45.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.071 seconds
[2024-07-30T18:54:16.286+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:54:16.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:54:16.287+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:54:16.287+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:54:16.294+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:54:16.293+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:54:16.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:54:16.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.072 seconds
[2024-07-30T18:54:46.604+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:54:46.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py for tasks to queue
[2024-07-30T18:54:46.606+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:54:46.605+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:54:46.614+0000] {logging_mixin.py:151} INFO - [2024-07-30T18:54:46.612+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py", line 9, in <module>
    from scripts.download_osm_data import download_osm_data
ModuleNotFoundError: No module named 'scripts'
[2024-07-30T18:54:46.615+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py
[2024-07-30T18:54:46.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/osm_to_geojson_to_html_mongodb_dag.py took 0.074 seconds
